
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Mar 26 2026 18:28:05 -03 (Mar 26 2026 21:28:05 UTC)

// Verification Directory fv/can_btu_top 

module can_btu_top(clk, rst_n, prescaler, prop_seg, phase_seg1,
     phase_seg2, sjw, can_rx, sync_en, hard_sync, bit_tick,
     sample_tick, tx_tick, sample_point, bit_time_cnt, sync_locked,
     edge_detected, sync_active, fsm_state);
  input clk, rst_n, can_rx, sync_en, hard_sync;
  input [7:0] prescaler;
  input [2:0] prop_seg, phase_seg1, phase_seg2;
  input [1:0] sjw;
  output bit_tick, sample_tick, tx_tick, sample_point, sync_locked,
       edge_detected, sync_active;
  output [7:0] bit_time_cnt;
  output [2:0] fsm_state;
  wire clk, rst_n, can_rx, sync_en, hard_sync;
  wire [7:0] prescaler;
  wire [2:0] prop_seg, phase_seg1, phase_seg2;
  wire [1:0] sjw;
  wire bit_tick, sample_tick, tx_tick, sample_point, sync_locked,
       edge_detected, sync_active;
  wire [7:0] bit_time_cnt;
  wire [2:0] fsm_state;
  wire [3:0] phase_seg2_adj;
  wire [3:0] phase_seg1_adj;
  wire [7:0] presc_counter;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, n_2,
       n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_38, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_100, n_101, n_102, n_103, n_104, n_106, n_107;
  wire n_108, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_163, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_199, n_201, n_202, n_203, n_204, n_205, n_207, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_274, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_302, n_303, n_304, n_305, n_306, n_307, n_308, n_309;
  wire n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342;
  wire n_343, n_344, n_345, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, phase_adjusted, presc_tick, prev_bus_value,
       sync_done;
  assign fsm_state[2] = 1'b0;
  assign bit_time_cnt[5] = 1'b0;
  assign bit_time_cnt[6] = 1'b0;
  assign bit_time_cnt[7] = 1'b0;
  DFFRX1 \phase_seg2_adj_reg[3] (.RN (rst_n), .CK (clk), .D (n_309), .Q
       (phase_seg2_adj[3]), .QN (UNCONNECTED));
  DFFRX1 \phase_seg1_adj_reg[3] (.RN (rst_n), .CK (clk), .D (n_308), .Q
       (phase_seg1_adj[3]), .QN (UNCONNECTED0));
  NOR2XL g19335__2398(.A (n_307), .B (n_306), .Y (n_309));
  NOR2XL g19334__5107(.A (n_307), .B (n_304), .Y (n_308));
  DFFSRXL \phase_seg1_adj_reg[2] (.RN (n_17), .SN (n_13), .CK (clk), .D
       (n_305), .Q (phase_seg1_adj[2]), .QN (n_2));
  DFFSRXL \phase_seg2_adj_reg[2] (.RN (n_4), .SN (n_9), .CK (clk), .D
       (n_302), .Q (phase_seg2_adj[2]), .QN (UNCONNECTED1));
  AOI21XL g19340__6260(.A0 (phase_seg2_adj[3]), .A1 (n_303), .B0
       (n_300), .Y (n_306));
  OAI222XL g19338__4319(.A0 (n_16), .A1 (n_283), .B0 (n_294), .B1
       (n_301), .C0 (n_2), .C1 (n_282), .Y (n_305));
  AOI22XL g19341__8428(.A0 (n_241), .A1 (n_299), .B0
       (phase_seg1_adj[3]), .B1 (n_303), .Y (n_304));
  MXI2XL g19339__5526(.A (n_257), .B (n_301), .S0 (n_297), .Y (n_302));
  NOR2XL g19342__6783(.A (n_280), .B (n_299), .Y (n_300));
  DFFSRXL \phase_seg1_adj_reg[1] (.RN (n_15), .SN (n_10), .CK (clk), .D
       (n_296), .Q (phase_seg1_adj[1]), .QN (UNCONNECTED2));
  DFFSRXL \phase_seg2_adj_reg[1] (.RN (n_8), .SN (n_11), .CK (clk), .D
       (n_298), .Q (phase_seg2_adj[1]), .QN (UNCONNECTED3));
  OAI21XL g19350__3680(.A0 (n_297), .A1 (n_259), .B0 (n_293), .Y
       (n_298));
  NAND2XL g19349__1617(.A (n_272), .B (n_295), .Y (n_296));
  NAND2XL g19352__2802(.A (n_186), .B (n_291), .Y (n_299));
  OAI21XL g19351__1705(.A0 (n_288), .A1 (n_290), .B0 (n_289), .Y
       (n_301));
  NAND2BXL g19354__5122(.AN (n_294), .B (n_292), .Y (n_295));
  NAND2XL g19353__8246(.A (n_297), .B (n_292), .Y (n_293));
  OAI21XL g19357__7098(.A0 (n_275), .A1 (n_202), .B0 (n_290), .Y
       (n_291));
  NAND2XL g19356__6131(.A (n_288), .B (n_290), .Y (n_289));
  ADDFX1 g19361__1881(.A (n_182), .B (n_265), .CI (n_277), .CO (n_290),
       .S (n_292));
  DFFRX1 \tq_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_286), .Q
       (bit_time_cnt[2]), .QN (n_183));
  DFFRX1 \tq_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_287), .Q
       (bit_time_cnt[1]), .QN (n_35));
  DFFSRXL \phase_seg2_adj_reg[0] (.RN (n_23), .SN (n_12), .CK (clk), .D
       (n_281), .Q (phase_seg2_adj[0]), .QN (n_27));
  DFFSRXL \phase_seg1_adj_reg[0] (.RN (n_21), .SN (n_18), .CK (clk), .D
       (n_284), .Q (phase_seg1_adj[0]), .QN (n_34));
  OAI31XL g19348__5115(.A0 (bit_time_cnt[1]), .A1 (n_267), .A2 (n_285),
       .B0 (n_278), .Y (n_287));
  OAI32XL g19347__7482(.A0 (bit_time_cnt[2]), .A1 (n_180), .A2 (n_285),
       .B0 (n_183), .B1 (n_273), .Y (n_286));
  OAI222XL g19372__4733(.A0 (n_276), .A1 (n_283), .B0 (n_294), .B1
       (n_279), .C0 (n_34), .C1 (n_282), .Y (n_284));
  OAI222XL g19373__6161(.A0 (n_28), .A1 (n_251), .B0 (n_280), .B1
       (n_279), .C0 (n_27), .C1 (n_282), .Y (n_281));
  DFFRX1 \tq_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_274), .Q
       (bit_time_cnt[3]), .QN (n_155));
  NAND2XL g19355__9315(.A (bit_time_cnt[1]), .B (n_266), .Y (n_278));
  OAI32XL g19379__9945(.A0 (n_276), .A1 (n_275), .A2 (n_271), .B0
       (n_264), .B1 (n_260), .Y (n_277));
  DFFRX1 \tq_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_270), .Q
       (bit_time_cnt[4]), .QN (n_238));
  DFFRX1 \tq_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_268), .Q
       (bit_time_cnt[0]), .QN (n_267));
  OAI33XL g19362__2883(.A0 (n_155), .A1 (n_218), .A2 (n_269), .B0
       (n_217), .B1 (bit_time_cnt[3]), .B2 (n_285), .Y (n_274));
  NOR2XL g19366__2346(.A (n_254), .B (n_263), .Y (n_273));
  AOI22XL g19377__1666(.A0 (phase_seg1[1]), .A1 (n_255), .B0
       (phase_seg1_adj[1]), .B1 (n_258), .Y (n_272));
  OAI21XL g19386__7410(.A0 (n_261), .A1 (n_271), .B0 (n_262), .Y
       (n_279));
  OAI22XL g19363__6417(.A0 (n_46), .A1 (n_285), .B0 (n_238), .B1
       (n_269), .Y (n_270));
  OAI22XL g19364__5477(.A0 (bit_time_cnt[0]), .A1 (n_285), .B0
       (presc_tick), .B1 (n_267), .Y (n_268));
  OAI21XL g19365__2398(.A0 (bit_time_cnt[0]), .A1 (n_269), .B0
       (presc_tick), .Y (n_266));
  MXI2XL g19389__5107(.A (n_275), .B (n_264), .S0 (n_252), .Y (n_265));
  NOR2XL g19367__6260(.A (n_166), .B (n_269), .Y (n_263));
  NAND2XL g19394__4319(.A (n_261), .B (n_271), .Y (n_262));
  NOR2XL g19395__8428(.A (phase_seg2[0]), .B (n_271), .Y (n_260));
  OAI22XL g19376__5526(.A0 (phase_seg2_adj[1]), .A1 (n_256), .B0
       (phase_seg2[1]), .B1 (n_258), .Y (n_259));
  OAI22XL g19375__6783(.A0 (phase_seg2_adj[2]), .A1 (n_256), .B0
       (phase_seg2[2]), .B1 (n_258), .Y (n_257));
  INVXL g19380(.A (n_283), .Y (n_255));
  NOR2XL g19368__3680(.A (n_254), .B (n_253), .Y (n_269));
  OAI21XL g19409__1617(.A0 (sjw[0]), .A1 (n_249), .B0 (n_250), .Y
       (n_271));
  NAND2XL g19369__2802(.A (presc_tick), .B (n_253), .Y (n_285));
  OAI21XL g19408__1705(.A0 (n_215), .A1 (n_246), .B0 (sjw[1]), .Y
       (n_252));
  INVXL g19381(.A (n_256), .Y (n_251));
  NOR2XL g19382__5122(.A (n_297), .B (n_248), .Y (n_283));
  NAND2XL g19383__8246(.A (n_294), .B (n_247), .Y (n_256));
  DFFRX1 \sync_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_245), .Q
       (fsm_state[0]), .QN (UNCONNECTED4));
  NAND2XL g19416__7098(.A (n_57), .B (n_249), .Y (n_250));
  AOI211XL g19374__6131(.A0 (bit_time_cnt[4]), .A1 (n_232), .B0
       (hard_sync), .C0 (n_239), .Y (n_253));
  INVXL g19391(.A (n_258), .Y (n_282));
  INVXL g19387(.A (n_247), .Y (n_248));
  DFFRX1 sync_active_reg(.RN (rst_n), .CK (clk), .D (n_243), .Q
       (sync_active), .QN (UNCONNECTED5));
  DFFRX1 sync_done_reg(.RN (rst_n), .CK (clk), .D (n_242), .Q
       (sync_done), .QN (UNCONNECTED6));
  DFFRX1 phase_adjusted_reg(.RN (rst_n), .CK (clk), .D (n_244), .Q
       (phase_adjusted), .QN (n_211));
  INVXL g19424(.A (n_249), .Y (n_246));
  OAI32XL g19397__1881(.A0 (hard_sync), .A1 (fsm_state[0]), .A2
       (n_234), .B0 (n_45), .B1 (n_307), .Y (n_258));
  NOR2XL g19398__5115(.A (n_307), .B (n_338), .Y (n_245));
  AOI21XL g19388__7482(.A0 (n_235), .A1 (n_240), .B0 (n_307), .Y
       (n_247));
  AOI21XL g19406__4733(.A0 (n_211), .A1 (n_233), .B0 (n_307), .Y
       (n_244));
  NOR2XL g19411__6161(.A (n_87), .B (n_307), .Y (n_243));
  AOI211XL g19427__9315(.A0 (n_189), .A1 (n_188), .B0 (n_190), .C0
       (n_230), .Y (n_249));
  NOR2XL g19412__9945(.A (n_38), .B (n_307), .Y (n_242));
  DFFRX1 \sync_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_236), .Q
       (fsm_state[1]), .QN (n_45));
  NAND2XL g19396__2883(.A (n_241), .B (n_240), .Y (n_294));
  AOI22XL g19378__2346(.A0 (n_195), .A1 (n_226), .B0 (n_238), .B1
       (n_231), .Y (n_239));
  OAI21XL g19413__7410(.A0 (n_235), .A1 (n_234), .B0 (n_29), .Y
       (n_236));
  NOR2XL g19417__6417(.A (hard_sync), .B (n_227), .Y (n_307));
  OAI21XL g19414__5477(.A0 (n_233), .A1 (n_234), .B0 (n_66), .Y
       (n_240));
  DFFRX1 sample_point_reg(.RN (rst_n), .CK (clk), .D (n_228), .Q
       (sample_point), .QN (UNCONNECTED7));
  INVXL g19384(.A (n_231), .Y (n_232));
  OAI211XL g19429__2398(.A0 (n_204), .A1 (n_203), .B0 (n_205), .C0
       (n_216), .Y (n_230));
  DFFRX1 tx_tick_reg(.RN (rst_n), .CK (clk), .D (n_225), .Q (tx_tick),
       .QN (UNCONNECTED8));
  DFFRX1 bit_tick_reg(.RN (rst_n), .CK (clk), .D (n_234), .Q
       (bit_tick), .QN (UNCONNECTED9));
  MX2XL g19407__6260(.A (sample_point), .B (n_212), .S0 (presc_tick),
       .Y (n_228));
  INVXL g19425(.A (n_234), .Y (n_227));
  AOI21XL g19385__4319(.A0 (n_222), .A1 (n_221), .B0 (n_223), .Y
       (n_231));
  DFFRX1 sample_tick_reg(.RN (rst_n), .CK (clk), .D (n_220), .Q
       (sample_tick), .QN (UNCONNECTED10));
  DFFRX1 \presc_counter_reg[3] (.RN (rst_n), .CK (clk), .D (n_351), .Q
       (presc_counter[3]), .QN (n_143));
  DFFRX1 \presc_counter_reg[1] (.RN (rst_n), .CK (clk), .D (n_214), .Q
       (presc_counter[1]), .QN (UNCONNECTED11));
  OAI31XL g19392__8428(.A0 (bit_time_cnt[3]), .A1 (n_175), .A2 (n_194),
       .B0 (n_210), .Y (n_226));
  NOR2XL g19426__5526(.A (n_267), .B (n_224), .Y (n_225));
  NOR2XL g19428__6783(.A (bit_time_cnt[0]), .B (n_224), .Y (n_234));
  NOR2XL g19393__3680(.A (n_222), .B (n_221), .Y (n_223));
  NOR3XL g19423__1617(.A (n_254), .B (n_192), .C (n_179), .Y (n_220));
  NOR2XL g19430__2802(.A (n_254), .B (n_217), .Y (n_218));
  NAND2XL g19454__1705(.A (n_5), .B (n_215), .Y (n_216));
  INVXL g19441(.A (n_213), .Y (n_214));
  DFFRX1 \presc_counter_reg[5] (.RN (rst_n), .CK (clk), .D (n_357), .Q
       (presc_counter[5]), .QN (n_163));
  OAI211XL g19446__5122(.A0 (presc_counter[1]), .A1 (presc_counter[0]),
       .B0 (n_339), .C0 (n_349), .Y (n_213));
  OAI22XL g19422__8246(.A0 (n_211), .A1 (n_193), .B0 (phase_adjusted),
       .B1 (n_264), .Y (n_212));
  INVXL g19404(.A (n_207), .Y (n_210));
  NAND2XL g19431__6131(.A (presc_tick), .B (n_50), .Y (n_224));
  DFFRX1 \presc_counter_reg[7] (.RN (rst_n), .CK (clk), .D (n_196), .Q
       (presc_counter[7]), .QN (UNCONNECTED12));
  DFFRX1 \presc_counter_reg[0] (.RN (rst_n), .CK (clk), .D (n_201), .Q
       (presc_counter[0]), .QN (UNCONNECTED13));
  DFFRX1 \presc_counter_reg[6] (.RN (rst_n), .CK (clk), .D (n_359), .Q
       (presc_counter[6]), .QN (UNCONNECTED14));
  DFFRX1 \presc_counter_reg[4] (.RN (rst_n), .CK (clk), .D (n_354), .Q
       (presc_counter[4]), .QN (UNCONNECTED15));
  DFFRX1 \presc_counter_reg[2] (.RN (rst_n), .CK (clk), .D (n_199), .Q
       (presc_counter[2]), .QN (n_3));
  ADDFX1 g19405__1881(.A (n_135), .B (n_174), .CI (n_171), .CO (n_221),
       .S (n_207));
  XOR2XL g19460__7482(.A (n_191), .B (n_187), .Y (n_215));
  AOI21XL g19458__4733(.A0 (n_204), .A1 (n_203), .B0 (n_6), .Y (n_205));
  OAI21XL g19466__6161(.A0 (n_264), .A1 (n_202), .B0 (n_185), .Y
       (n_288));
  NOR2XL g19445__9315(.A (presc_counter[0]), .B (n_348), .Y (n_201));
  NOR2XL g19447__9945(.A (n_42), .B (n_348), .Y (n_199));
  NOR2XL g19453__1666(.A (n_79), .B (n_348), .Y (n_196));
  DFFRX1 presc_tick_reg(.RN (rst_n), .CK (clk), .D (n_348), .Q
       (presc_tick), .QN (n_254));
  AOI21XL g19415__7410(.A0 (bit_time_cnt[3]), .A1 (n_194), .B0 (n_178),
       .Y (n_195));
  AOI22XL g19444__6417(.A0 (n_127), .A1 (n_181), .B0 (bit_time_cnt[4]),
       .B1 (n_114), .Y (n_193));
  OAI221XL g19464__5477(.A0 (n_211), .A1 (n_74), .B0 (phase_adjusted),
       .B1 (n_191), .C0 (n_184), .Y (n_192));
  NOR2XL g19465__2398(.A (n_189), .B (n_188), .Y (n_190));
  OAI221XL g19470__5107(.A0 (n_56), .A1 (n_264), .B0 (bit_time_cnt[0]),
       .B1 (n_275), .C0 (n_55), .Y (n_187));
  OAI221XL g19471__4319(.A0 (bit_time_cnt[1]), .A1 (n_275), .B0
       (n_149), .B1 (n_264), .C0 (n_76), .Y (n_203));
  NAND2XL g19477__8428(.A (n_186), .B (n_185), .Y (n_202));
  AOI211XL g19473__5526(.A0 (n_267), .A1 (n_70), .B0 (n_71), .C0
       (n_172), .Y (n_184));
  OAI222XL g19467__6783(.A0 (bit_time_cnt[2]), .A1 (n_275), .B0
       (n_133), .B1 (n_264), .C0 (n_140), .C1 (n_183), .Y (n_188));
  OAI22XL g19479__3680(.A0 (n_14), .A1 (n_275), .B0 (n_7), .B1 (n_264),
       .Y (n_182));
  OAI22XL g19478__1617(.A0 (phase_seg1[0]), .A1 (n_275), .B0
       (phase_seg2[0]), .B1 (n_264), .Y (n_261));
  INVXL g19485(.A (n_297), .Y (n_280));
  OAI211XL g19463__2802(.A0 (n_177), .A1 (n_154), .B0 (n_158), .C0
       (n_167), .Y (n_181));
  AOI32XL g19432__1705(.A0 (n_180), .A1 (n_128), .A2 (n_130), .B0
       (n_183), .B1 (n_176), .Y (n_194));
  AOI32XL g19462__5122(.A0 (phase_adjusted), .A1 (n_160), .A2 (n_165),
       .B0 (n_211), .B1 (n_118), .Y (n_179));
  NAND2XL g19487__8246(.A (phase_seg1[2]), .B (n_264), .Y (n_185));
  NOR2XL g19489__7098(.A (n_233), .B (n_264), .Y (n_297));
  NOR2XL g19442__6131(.A (n_177), .B (n_176), .Y (n_178));
  NOR2XL g19443__1881(.A (n_98), .B (n_176), .Y (n_175));
  OAI21XL g19468__5115(.A0 (n_169), .A1 (n_168), .B0 (n_170), .Y
       (n_174));
  NAND2XL g19488__4733(.A (phase_seg2[2]), .B (n_275), .Y (n_186));
  NOR2XL g19486__6161(.A (n_233), .B (n_275), .Y (n_241));
  NOR2XL g19475__9315(.A (n_148), .B (n_161), .Y (n_222));
  OAI22XL g19482__9945(.A0 (bit_time_cnt[4]), .A1 (n_153), .B0 (n_238),
       .B1 (n_152), .Y (n_172));
  INVXL g19494(.A (n_275), .Y (n_264));
  ADDFX1 g19457__2883(.A (n_93), .B (n_129), .CI (n_136), .CO (n_171),
       .S (n_176));
  NAND2XL g19474__2346(.A (n_169), .B (n_168), .Y (n_170));
  OAI21XL g19472__1666(.A0 (n_166), .A1 (n_75), .B0 (n_165), .Y
       (n_167));
  OR4X1 g19498__6417(.A (bit_time_cnt[4]), .B (n_122), .C (n_134), .D
       (n_150), .Y (n_275));
  INVXL g19480(.A (n_168), .Y (n_161));
  AOI22XL g19481__5477(.A0 (bit_time_cnt[3]), .A1 (n_156), .B0
       (bit_time_cnt[2]), .B1 (n_157), .Y (n_160));
  OAI222XL g19496__2398(.A0 (n_113), .A1 (presc_counter[5]), .B0
       (n_144), .B1 (n_147), .C0 (n_107), .C1 (presc_counter[4]), .Y
       (n_159));
  OAI21XL g19491__5107(.A0 (bit_time_cnt[3]), .A1 (n_157), .B0 (n_156),
       .Y (n_158));
  AOI22XL g19483__6260(.A0 (n_155), .A1 (n_151), .B0 (n_183), .B1
       (n_154), .Y (n_165));
  AOI21XL g19503__4319(.A0 (n_211), .A1 (n_189), .B0 (n_152), .Y
       (n_153));
  AOI22XL g19484__8428(.A0 (phase_adjusted), .A1 (n_151), .B0 (n_115),
       .B1 (n_211), .Y (n_168));
  AOI21XL g19504__5526(.A0 (n_149), .A1 (n_54), .B0 (n_141), .Y
       (n_150));
  OAI22XL g19490__3680(.A0 (phase_seg2_adj[3]), .A1 (n_131), .B0
       (n_169), .B1 (n_126), .Y (n_148));
  INVXL g19499(.A (n_151), .Y (n_156));
  AOI21XL g19512__1617(.A0 (n_143), .A1 (n_142), .B0 (n_92), .Y
       (n_147));
  NOR2XL g19520__1705(.A (n_143), .B (n_142), .Y (n_144));
  AOI21XL g19502__5122(.A0 (n_120), .A1 (n_119), .B0 (n_121), .Y
       (n_151));
  OAI211XL g19511__8246(.A0 (n_140), .A1 (bit_time_cnt[2]), .B0
       (n_137), .C0 (n_44), .Y (n_141));
  NAND2XL g19532__7098(.A (n_123), .B (n_137), .Y (n_189));
  OAI21XL g19501__6131(.A0 (n_117), .A1 (n_116), .B0 (n_135), .Y
       (n_136));
  AOI21XL g19521__1881(.A0 (n_108), .A1 (n_177), .B0 (n_133), .Y
       (n_134));
  INVXL g19506(.A (n_152), .Y (n_131));
  OAI21XL g19500__7482(.A0 (n_129), .A1 (n_106), .B0 (n_22), .Y
       (n_130));
  OAI211XL g19492__4733(.A0 (bit_time_cnt[1]), .A1 (n_129), .B0 (n_69),
       .C0 (n_335), .Y (n_128));
  NAND2XL g19507__6161(.A (n_238), .B (n_126), .Y (n_127));
  INVXL g19537(.A (n_122), .Y (n_123));
  NOR2XL g19508__9945(.A (n_120), .B (n_119), .Y (n_121));
  AOI21XL g19530__2883(.A0 (n_94), .A1 (presc_counter[2]), .B0 (n_110),
       .Y (n_142));
  INVXL g19524(.A (n_204), .Y (n_118));
  NAND2XL g19510__2346(.A (n_117), .B (n_116), .Y (n_135));
  NOR2XL g19539__1666(.A (n_115), .B (n_155), .Y (n_122));
  NOR2XL g19509__7410(.A (n_211), .B (n_114), .Y (n_152));
  INVXL g19523(.A (n_112), .Y (n_113));
  NAND2BXL g19540__6417(.AN (n_111), .B (prescaler[7]), .Y (n_132));
  NAND2XL g19535__5477(.A (n_115), .B (n_155), .Y (n_137));
  AOI21XL g19514__2398(.A0 (prescaler[6]), .A1 (n_336), .B0 (n_111), .Y
       (n_145));
  AOI211XL g19534__5107(.A0 (n_67), .A1 (n_339), .B0 (n_95), .C0
       (n_68), .Y (n_110));
  OAI21XL g19518__6260(.A0 (phase_seg1_adj[3]), .A1 (n_102), .B0
       (n_100), .Y (n_119));
  INVXL g19516(.A (n_114), .Y (n_126));
  NAND2XL g19538__4319(.A (n_101), .B (bit_time_cnt[2]), .Y (n_108));
  AOI21XL g19541__5526(.A0 (prescaler[5]), .A1 (n_103), .B0 (n_97), .Y
       (n_112));
  AOI22XL g19536__6783(.A0 (n_140), .A1 (n_183), .B0 (n_133), .B1
       (bit_time_cnt[2]), .Y (n_204));
  NOR2XL g19525__3680(.A (n_335), .B (n_104), .Y (n_106));
  OAI22XL g19517__1617(.A0 (n_211), .A1 (n_154), .B0 (n_133), .B1
       (phase_adjusted), .Y (n_116));
  AND2XL g19527__2802(.A (n_335), .B (n_104), .Y (n_129));
  NOR3BXL g19548__1705(.AN (n_103), .B (prescaler[5]), .C
       (prescaler[6]), .Y (n_111));
  OAI21XL g19519__5122(.A0 (n_96), .A1 (n_102), .B0
       (phase_seg1_adj[3]), .Y (n_114));
  INVXL g19545(.A (n_101), .Y (n_115));
  NAND2XL g19529__8246(.A (phase_seg1_adj[3]), .B (n_102), .Y (n_100));
  NOR2XL g19526__6131(.A (n_98), .B (n_154), .Y (n_157));
  NOR2XL g19542__1881(.A (prescaler[5]), .B (n_103), .Y (n_97));
  AOI21XL g19522__5115(.A0 (prescaler[4]), .A1 (n_337), .B0 (n_103), .Y
       (n_107));
  NOR2XL g19549__7482(.A (n_96), .B (n_91), .Y (n_101));
  NOR2XL g19552__4733(.A (n_94), .B (presc_counter[2]), .Y (n_95));
  OAI21XL g19543__6161(.A0 (n_85), .A1 (n_84), .B0 (n_93), .Y (n_104));
  AOI21XL g19546__9315(.A0 (prescaler[3]), .A1 (n_88), .B0 (n_83), .Y
       (n_92));
  INVXL g19550(.A (n_133), .Y (n_140));
  ADDFX1 g19551__9945(.A (phase_seg1[2]), .B (n_90), .CI (n_59), .CO
       (n_91), .S (n_133));
  ADDFX1 g19533__2883(.A (n_90), .B (phase_seg1_adj[2]), .CI (n_60),
       .CO (n_102), .S (n_154));
  NOR3BXL g19556__1666(.AN (n_88), .B (prescaler[3]), .C
       (prescaler[4]), .Y (n_103));
  AOI22XL g19570__7410(.A0 (n_235), .A1 (n_77), .B0 (sync_active), .B1
       (n_86), .Y (n_87));
  NAND2XL g19553__6417(.A (n_85), .B (n_84), .Y (n_93));
  NOR2XL g19554__5477(.A (prescaler[3]), .B (n_88), .Y (n_83));
  AOI21XL g19565__5107(.A0 (prescaler[2]), .A1 (n_72), .B0 (n_88), .Y
       (n_94));
  AOI21XL g19493__4319(.A0 (presc_counter[6]), .A1 (n_356), .B0
       (presc_counter[7]), .Y (n_79));
  NOR2BX1 g19575__8428(.AN (n_235), .B (n_77), .Y (n_78));
  OAI21XL g19561__5526(.A0 (n_149), .A1 (bit_time_cnt[1]), .B0 (n_76),
       .Y (n_191));
  AOI22XL g19559__6783(.A0 (n_49), .A1 (n_73), .B0 (n_43), .B1 (n_41),
       .Y (n_75));
  MXI2XL g19557__3680(.A (bit_time_cnt[1]), .B (n_35), .S0 (n_73), .Y
       (n_74));
  OAI22XL g19558__1617(.A0 (n_149), .A1 (phase_adjusted), .B0 (n_211),
       .B1 (n_73), .Y (n_84));
  NOR2XL g19569__2802(.A (prescaler[2]), .B (n_72), .Y (n_88));
  NOR2XL g19579__1705(.A (n_267), .B (n_70), .Y (n_71));
  NAND2XL g19578__5122(.A (n_36), .B (n_70), .Y (n_69));
  AOI211XL g19564__7098(.A0 (n_61), .A1 (presc_counter[0]), .B0 (n_62),
       .C0 (presc_counter[1]), .Y (n_68));
  INVXL g19571(.A (n_72), .Y (n_67));
  OAI21XL g19583__6131(.A0 (n_47), .A1 (sync_done), .B0 (n_66), .Y
       (n_77));
  NAND2XL g19566__1881(.A (n_149), .B (bit_time_cnt[1]), .Y (n_76));
  DFFRX1 sync_locked_reg(.RN (rst_n), .CK (clk), .D (n_51), .Q
       (sync_locked), .QN (UNCONNECTED16));
  NAND2XL g19573__4733(.A (n_62), .B (n_61), .Y (n_72));
  ADDFX1 g19567__6161(.A (n_58), .B (phase_seg1_adj[1]), .CI (n_33),
       .CO (n_60), .S (n_73));
  ADDFX1 g19568__9315(.A (phase_seg1[1]), .B (n_32), .CI (n_58), .CO
       (n_59), .S (n_149));
  AOI22XL g19586__9945(.A0 (n_53), .A1 (n_211), .B0 (phase_adjusted),
       .B1 (n_48), .Y (n_70));
  OAI21XL g19587__2883(.A0 (n_56), .A1 (bit_time_cnt[0]), .B0 (n_55),
       .Y (n_57));
  OAI21XL g19588__2346(.A0 (n_53), .A1 (bit_time_cnt[0]), .B0
       (bit_time_cnt[1]), .Y (n_54));
  NAND3BXL g19584__7410(.AN (sync_done), .B (n_267), .C (n_50), .Y
       (n_51));
  NAND2XL g19590__5477(.A (bit_time_cnt[1]), .B (n_48), .Y (n_49));
  NAND2XL g19593__2398(.A (sync_en), .B (edge_detected), .Y (n_47));
  NOR2XL g19576__5107(.A (prescaler[0]), .B (n_361), .Y (n_61));
  OR2XL g19599__6260(.A (n_155), .B (n_217), .Y (n_46));
  OAI21XL g19601__4319(.A0 (hard_sync), .A1 (n_30), .B0 (n_45), .Y
       (n_303));
  NAND2XL g19591__8428(.A (n_56), .B (n_43), .Y (n_44));
  NAND2XL g19595__5526(.A (n_56), .B (bit_time_cnt[0]), .Y (n_55));
  AOI21XL g19585__6783(.A0 (presc_counter[2]), .A1 (n_339), .B0 (n_31),
       .Y (n_42));
  INVXL g19598(.A (n_41), .Y (n_48));
  NOR2XL g19602__2802(.A (sync_done), .B (n_26), .Y (n_38));
  INVXL g19597(.A (n_56), .Y (n_53));
  DFFRX1 edge_detected_int_reg(.RN (rst_n), .CK (clk), .D (n_25), .Q
       (edge_detected), .QN (UNCONNECTED17));
  AND3XL g19600__1705(.A (n_238), .B (n_35), .C (n_98), .Y (n_50));
  NAND2XL g19610__5122(.A (bit_time_cnt[2]), .B (n_166), .Y (n_217));
  XNOR2X1 g19589__8246(.A (n_24), .B (prop_seg[2]), .Y (n_90));
  INVXL g19577(.A (n_120), .Y (n_96));
  AOI21XL g19613__7098(.A0 (prop_seg[0]), .A1 (n_34), .B0 (n_33), .Y
       (n_41));
  AOI21XL g19615__6131(.A0 (prop_seg[0]), .A1 (n_276), .B0 (n_32), .Y
       (n_56));
  NOR2XL g19592__1881(.A (presc_counter[2]), .B (n_339), .Y (n_31));
  INVXL g19618(.A (n_233), .Y (n_30));
  NAND2XL g19606__5115(.A (hard_sync), .B (n_86), .Y (n_29));
  AOI22XL g19607__4733(.A0 (n_28), .A1 (n_211), .B0 (n_27), .B1
       (phase_adjusted), .Y (n_36));
  AOI21XL g19612__6161(.A0 (n_66), .A1 (n_45), .B0 (fsm_state[0]), .Y
       (n_26));
  NOR2XL g19611__9315(.A (can_rx), .B (prev_bus_value), .Y (n_25));
  OAI22XL g19608__9945(.A0 (phase_seg2[2]), .A1 (phase_adjusted), .B0
       (phase_seg2_adj[2]), .B1 (n_211), .Y (n_117));
  OAI22XL g19609__2883(.A0 (phase_seg2[1]), .A1 (phase_adjusted), .B0
       (phase_seg2_adj[1]), .B1 (n_211), .Y (n_85));
  NAND2BXL g19596__2346(.AN (n_24), .B (prop_seg[2]), .Y (n_120));
  NAND2XL g19637__1666(.A (n_20), .B (n_28), .Y (n_23));
  INVXL g19616(.A (n_43), .Y (n_22));
  NAND2XL g19634__7410(.A (n_20), .B (n_276), .Y (n_21));
  NOR2XL g19645__5477(.A (prop_seg[0]), .B (n_276), .Y (n_32));
  NOR2XL g19629__2398(.A (prop_seg[0]), .B (n_34), .Y (n_33));
  XOR2XL g19614__5107(.A (prop_seg[0]), .B (prop_seg[1]), .Y (n_58));
  INVXL g19617(.A (n_180), .Y (n_166));
  NAND2XL g19631__6260(.A (fsm_state[0]), .B (n_45), .Y (n_233));
  NAND2XL g19641__4319(.A (phase_seg1[0]), .B (n_20), .Y (n_18));
  NAND2XL g19633__8428(.A (n_20), .B (n_16), .Y (n_17));
  NAND2XL g19635__5526(.A (n_20), .B (n_14), .Y (n_15));
  NAND2XL g19642__6783(.A (phase_seg1[2]), .B (n_20), .Y (n_13));
  NAND2XL g19632__3680(.A (phase_seg2[0]), .B (n_20), .Y (n_12));
  NAND2XL g19643__1617(.A (phase_seg2[1]), .B (n_20), .Y (n_11));
  NAND2XL g19640__2802(.A (phase_seg1[1]), .B (n_20), .Y (n_10));
  NAND2XL g19639__1705(.A (phase_seg2[2]), .B (n_20), .Y (n_9));
  NAND2XL g19619__5122(.A (n_20), .B (n_7), .Y (n_8));
  NAND2XL g19630__8246(.A (bit_time_cnt[1]), .B (bit_time_cnt[0]), .Y
       (n_180));
  NAND2XL g19622__7098(.A (phase_seg2_adj[3]), .B (phase_adjusted), .Y
       (n_169));
  NAND2XL g19625__6131(.A (bit_time_cnt[3]), .B (bit_time_cnt[2]), .Y
       (n_177));
  NAND2XL g19626__1881(.A (fsm_state[1]), .B (fsm_state[0]), .Y (n_86));
  NOR2XL g19623__5115(.A (bit_time_cnt[1]), .B (bit_time_cnt[0]), .Y
       (n_43));
  NOR2XL g19620__4733(.A (sjw[0]), .B (sjw[1]), .Y (n_6));
  NAND2XL g19638__6161(.A (sjw[0]), .B (sjw[1]), .Y (n_5));
  DFFSX1 prev_bus_value_reg(.SN (rst_n), .CK (clk), .D (can_rx), .Q
       (UNCONNECTED18), .QN (prev_bus_value));
  OR2XL g19636__9315(.A (phase_seg2[2]), .B (rst_n), .Y (n_4));
  NAND2XL g19644__9945(.A (prop_seg[0]), .B (prop_seg[1]), .Y (n_24));
  NOR2XL g19624__2883(.A (bit_time_cnt[3]), .B (bit_time_cnt[2]), .Y
       (n_98));
  NOR2XL g19627__2346(.A (fsm_state[0]), .B (fsm_state[1]), .Y (n_235));
  INVXL g19658(.A (prescaler[1]), .Y (n_62));
  INVXL g19667(.A (phase_seg1[2]), .Y (n_16));
  INVXL g19666(.A (phase_seg1[1]), .Y (n_14));
  INVXL g19660(.A (phase_seg2[1]), .Y (n_7));
  INVXL g19665(.A (hard_sync), .Y (n_66));
  INVXL g19663(.A (phase_seg2[0]), .Y (n_28));
  INVXL g19664(.A (phase_seg1[0]), .Y (n_276));
  INVXL g19668(.A (rst_n), .Y (n_20));
  OR2XL g2(.A (n_70), .B (n_36), .Y (n_335));
  NAND2BXL g19703(.AN (prescaler[5]), .B (n_103), .Y (n_336));
  NAND2BXL g19704(.AN (prescaler[3]), .B (n_88), .Y (n_337));
  OA22X1 g19705(.A0 (fsm_state[0]), .A1 (n_78), .B0 (n_86), .B1
       (n_234), .Y (n_338));
  INVXL g292(.A (n_350), .Y (n_351));
  OAI211XL g293(.A0 (presc_counter[3]), .A1 (n_340), .B0 (n_341), .C0
       (n_349), .Y (n_350));
  NOR2XL g302(.A (n_3), .B (n_339), .Y (n_340));
  NAND2XL g305(.A (presc_counter[1]), .B (presc_counter[0]), .Y
       (n_339));
  NAND2XL g301(.A (presc_counter[3]), .B (n_340), .Y (n_341));
  INVXL g294(.A (n_348), .Y (n_349));
  OAI221X1 g295(.A0 (n_343), .A1 (n_346), .B0 (n_343), .B1 (n_159), .C0
       (n_347), .Y (n_348));
  OAI21XL g303(.A0 (n_145), .A1 (presc_counter[6]), .B0 (n_342), .Y
       (n_343));
  OR2XL g307(.A (n_132), .B (presc_counter[7]), .Y (n_342));
  AOI31X1 g299(.A0 (n_107), .A1 (presc_counter[4]), .A2 (n_344), .B0
       (n_345), .Y (n_346));
  NAND2XL g306(.A (n_112), .B (n_163), .Y (n_344));
  NOR2XL g304(.A (n_112), .B (n_163), .Y (n_345));
  AOI32XL g300(.A0 (n_145), .A1 (presc_counter[6]), .A2 (n_342), .B0
       (n_132), .B1 (presc_counter[7]), .Y (n_347));
  NOR2XL g290(.A (n_353), .B (n_348), .Y (n_354));
  AOI21XL g296(.A0 (presc_counter[4]), .A1 (n_341), .B0 (n_352), .Y
       (n_353));
  NOR2XL g297(.A (presc_counter[4]), .B (n_341), .Y (n_352));
  NOR2XL g291(.A (n_163), .B (n_355), .Y (n_356));
  NAND2BXL g298(.AN (n_341), .B (presc_counter[4]), .Y (n_355));
  AOI211XL g289(.A0 (n_163), .A1 (n_355), .B0 (n_356), .C0 (n_348), .Y
       (n_357));
  NOR2XL g287(.A (n_358), .B (n_348), .Y (n_359));
  XNOR2X1 g288(.A (presc_counter[6]), .B (n_356), .Y (n_358));
  NOR4X1 g48(.A (prescaler[4]), .B (prescaler[7]), .C (prescaler[6]),
       .D (n_360), .Y (n_361));
  OR4X1 g49(.A (prescaler[3]), .B (prescaler[5]), .C (prescaler[1]), .D
       (prescaler[2]), .Y (n_360));
endmodule

